# Generated by Django 5.0.3 on 2024-03-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField()),
                ('completed', models.BooleanField(default=True)),
                ('parent_task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.task')),
            ],
        ),
    ]
