# Generated by Django 5.0.3 on 2024-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=40)),
                ('age', models.BigIntegerField(max_length=2)),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=25)),
                ('age', models.BigIntegerField(max_length=2)),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=25)),
                ('age', models.BigIntegerField(max_length=2)),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ExoticAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_of_origin', models.CharField(max_length=40)),
                ('age', models.BigIntegerField(max_length=2)),
                ('vaccinated', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=25)),
                ('type_of_animal', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField(max_length=2)),
                ('number_of_pets', models.IntegerField(max_length=1)),
            ],
        ),
    ]
