# Generated by Django 5.0.3 on 2024-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0003_alter_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
