# Generated by Django 5.0.3 on 2024-03-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0004_alter_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
    ]
