# Generated by Django 5.0.3 on 2024-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('student_email', models.EmailField(max_length=60)),
                ('personal_email', models.EmailField(max_length=60)),
                ('locker_number', models.IntegerField()),
                ('locker_combination', models.CharField()),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
