# Generated by Django 5.0.3 on 2024-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_alter_student_id'),
        ('subject_app', '0005_remove_subject_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='subject_app.subject'),
        ),
    ]
